### ISSUE TITLE
fails if not in worktree (PR)

### ISSUE THREAD

**Issue by mralusw** [Kristian-Tan/git-worktree-relative#1]
Running any of the scripts in the main repo (instead of a worktree) result in nasty compounded errors.

There are absolutely no checks that any of the `readlink` etc commands succeed. I would suggest `#!/bin/bash -eu`, or at least `-u`, but for the time being I'll add a sanity check if `cat .gitdir` fails (this catches most problems).

Also, `verbose_output` should go to stderr, not stdout; I'll make a separate PR.

**Comment by mralusw** [comment]
https://github.com/Kristian-Tan/git-worktree-relative/pull/2

**Comment by Kristian-Tan** [comment]
solved in PR #2
