### ISSUE TITLE
verbose_output -> stderr

### ISSUE THREAD

**Issue by mralusw** [Kristian-Tan/git-worktree-relative#4]
It's better to leave stdout for the script *output* (in case it needs to be reused by another script, e.g. you may wish to output some final path) and print diagnostics / debugging / logging to stderr.

Also on PR https://github.com/Kristian-Tan/git-worktree-relative/pull/2 since for some reason `gh` doesn't create new PRs

**Comment by Kristian-Tan** [comment]
solved in PR #2
