### ISSUE TITLE
tac: command not found

### ISSUE THREAD

**Issue by fantouch** [Kristian-Tan/git-worktree-relative#5]
```bash
$ git-worktree-relative -r ./my-repo -d
git-worktree-relative: line 127: tac: command not found
git-worktree-relative: line 132: tac: command not found
git-worktree-relative: line 142: tac: command not found
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

**Comment by Kristian-Tan** [comment]
After quick googling, it seems that this issue occurs only on macOS. Is that true? Are you using macOS @fantouch ?

**Comment by Kristian-Tan** [comment]
On macOS, you may try methods suggested here: https://unix.stackexchange.com/questions/114041/how-can-i-get-the-tac-command-on-os-x

alternative 1: use brew to install gnu coreutils
```
brew install coreutils
```

alternative 2: define function in /etc/bashrc
```
tac() { tail -r -- "$@"; }
```

I will add this to README.md if you confirmed that it solves this issue

**Comment by fantouch** [comment]
Yes macOS, thanks the suggestion works

**Comment by Kristian-Tan** [comment]
I've added this solution in README.md 
https://github.com/Kristian-Tan/git-worktree-relative/blob/master/README.md#installation-on-macos
